#!/usr/bin/perl -w

use strict;

# усреднить по дням "дату - время - температуру - снег"
# дата в формате DD/MM


my %data;
foreach (<>){
  next if /^#/;
  my ($d, $t, $T, $s, $w) = split(/\s+/);
  $d=~/(\d\d)\.(\d\d)/;
  my $d1 = "$2.$1"; # MM.DD for sorting
  push @{$data{$d1}}, {d=>$d, t=>$t, T=>$T, s=>$s, w=>$w};
}

foreach my $d1 (sort keys %data){
  $a = $data{$d1};
  my $Ta = 0;
  my $nt = 0;
  my $Wa = 0;
  my $nw = 0;

  my $sm = '';
  my $d = 0;
  foreach (@{$a}){
    $d = $_->{d};
    if ($_->{T} =~ /[0-9\.]+/){
      $Ta += $_->{T};
      $nt +=1;
    }
    if ($_->{w} =~ /[0-9\.]+/){
      $Wa += $_->{w};
      $nw +=1;
    }

    if ($_->{s} =~ /[0-9\.]+/){
      $sm = $_->{s} if ($sm !~ /[0-9\.]+/) || ($_->{s} > $sm);
    }
  }
  if ($nt>0) { $Ta /= $nt} else {$Ta=''};
  if ($nw>0) { $Wa /= $nw} else {$Wa=''};

  printf "%5s", $d;
  if ($Ta =~ /[0-9\.]+/){ printf "\t%6.2f", $Ta;  } else { print "\t-"; }
  if ($sm =~ /[0-9\.]+/){ printf "\t%4.1f", $sm;  } else { print "\t-"; }
  if ($Wa =~ /[0-9\.]+/){ printf "\t%4.1f", $Wa;  } else { print "\t-"; }
  print "\n";
}
